### ISSUE TITLE
Default page title is unchanged

### ISSUE THREAD

**Issue by ne1ox** [Erasmus2024/Strona-Erasmus-2024#11]
![image](https://github.com/Erasmus2024/Strona-Erasmus-2024/assets/44135502/b905b05f-ab9e-4145-9839-fd46f193c961)
You must have forgotten to change the page title, which looks really unprofessional. I suggest doing the same thing they did with the previous pages. Here is an example:

![image](https://github.com/Erasmus2024/Strona-Erasmus-2024/assets/44135502/22607d58-6706-4120-8b64-643ee62432ce)

**Comment by KamilCodemate** [comment]
You're right, we forgot about it, we'll figure it out soon

**Comment by KamilCodemate** [comment]
You're right, we forgot about it, we'll get it soon, thanks for reminding us
